---
version: "3.7"
services:
  web:
    image: "ghcr.io/uwcirg/sdc-services:${DOCKER_IMAGE_TAG:-main}"
    build:
      context: .
    ports:
      # allow override of published port
      - ${P_PORT:-5000}:5000
    env_file:
      - sdc_services.env
