---
version: "3.7"
services:
  web:
    image: "uwcirg/sdc-services:${DOCKER_IMAGE_TAG:-develop}"
    build:
      context: .
    ports:
      # allow override of published port
      - ${P_PORT:-5000}:5000
    env_file:
      - sdc_services.env
