# docker-compose development overrides
# mount code checkout into container and use development server for auto-reloading
---
version: "3.7"
services:
  web:
    environment:
      FLASK_DEBUG: 1
    volumes:
      - ./:/opt/app
